### ISSUE TITLE
Image optimization not working on nodejitsu

### ISSUE THREAD

**Issue by Nevtep** [niftylettuce/express-cdn#37]
Nick, I've switched to 0.1.0 with the compiled bins and I started getting some nasty errors on my app. Here is the log:

```
[04/19 12:01:26 GMT-0300] Unsupported platform: sunos x64
[04/19 12:01:26 GMT-0300] Unsupported platform: sunos x64
[04/19 12:01:26 GMT-0300] info: [object Object]
[04/19 12:01:26 GMT-0300] child_process.js:782
[04/19 12:01:26 GMT-0300]   var r = this._handle.spawn(options);
[04/19 12:01:26 GMT-0300]                        ^
[04/19 12:01:26 GMT-0300] TypeError: Bad argument
[04/19 12:01:26 GMT-0300]     at ChildProcess.spawn (child_process.js:782:24)
[04/19 12:01:26 GMT-0300]     at exports.spawn (child_process.js:618:9)
[04/19 12:01:26 GMT-0300]     at compile (/opt/haibu/apps/realfilling/FarmShares
QA/package/node_modules/express-cdn/lib/main.js:233:23)
[04/19 12:01:26 GMT-0300]     at checkStringIfModified (/opt/haibu/apps/realfill
ing/FarmSharesQA/package/node_modules/express-cdn/lib/main.js:392:91)
[04/19 12:01:26 GMT-0300]     at ClientRequest.onResponse (/opt/haibu/apps/realf
illing/FarmSharesQA/package/node_modules/express-cdn/node_modules/knox/lib/clien
t.js:49:7)
[04/19 12:01:26 GMT-0300]     at ClientRequest.EventEmitter.emit (events.js:96:1
7)
[04/19 12:01:26 GMT-0300]     at HTTPParser.parserOnIncomingClient [as onIncomin
g] (http.js:1582:7)
[04/19 12:01:26 GMT-0300]     at HTTPParser.parserOnHeadersComplete [as onHeader
sComplete] (http.js:111:23)
[04/19 12:01:26 GMT-0300]     at CleartextStream.socketOnData [as ondata] (http.
js:1485:20)
[04/19 12:01:26 GMT-0300]     at CleartextStream.CryptoStream._push (tls.js:544:
27)
[04/19 12:01:26 GMT-0300] info: [object Object]
[04/19 12:01:28 GMT-0300] info: All dependencies loaded, preparing to configure
qa environment.
[04/19 12:01:29 GMT-0300] info: Database connected.
[04/19 12:01:30 GMT-0300] info: FarmShares server listening on port: 80
[04/19 12:01:30 GMT-0300] Unsupported platform: sunos x64
[04/19 12:01:31 GMT-0300] info: [object Object]
[04/19 12:01:31 GMT-0300] child_process.js:782
[04/19 12:01:31 GMT-0300]   var r = this._handle.spawn(options);
[04/19 12:01:31 GMT-0300]                        ^
```

**Comment by gagalago** [comment]
some update ? can I close ?
