### ISSUE TITLE
Error with bin files

### ISSUE THREAD

**Issue by Nevtep** [niftylettuce/express-cdn#39]
I keep getting this error, any ideas?:

[04/25 06:24:59 GMT-0300] child_process.js:782
[04/25 06:24:59 GMT-0300]   var r = this._handle.spawn(options);
[04/25 06:24:59 GMT-0300]                        ^
[04/25 06:24:59 GMT-0300] TypeError: Bad argument
[04/25 06:24:59 GMT-0300]     at ChildProcess.spawn (child_process.js:782:24)
[04/25 06:24:59 GMT-0300]     at exports.spawn (child_process.js:618:9)
[04/25 06:24:59 GMT-0300]     at compile (/opt/haibu/apps/realfilling/FarmSharesStaging/package/node_modules/expres
s-cdn/lib/main.js:267:24)
[04/25 06:24:59 GMT-0300]     at checkStringIfModified (/opt/haibu/apps/realfilling/FarmSharesStaging/package/node_
modules/express-cdn/lib/main.js:397:92)
[04/25 06:24:59 GMT-0300]     at ClientRequest.onResponse (/opt/haibu/apps/realfilling/FarmSharesStaging/package/no
de_modules/express-cdn/node_modules/knox/lib/client.js:49:7)
[04/25 06:24:59 GMT-0300]     at ClientRequest.EventEmitter.emit (events.js:96:17)
[04/25 06:24:59 GMT-0300]     at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1544:7)
[04/25 06:24:59 GMT-0300]     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:111:23)
[04/25 06:24:59 GMT-0300]     at CleartextStream.socketOnData [as ondata](http.js:1447:20)
[04/25 06:24:59 GMT-0300]     at CleartextStream.CryptoStream._push (tls.js:544:27)

**Comment by gagalago** [comment]
some update ? can I close ?
