### ISSUE TITLE
CSS minification breaks if background image is base encoded

### ISSUE THREAD

**Issue by thebyrd** [niftylettuce/express-cdn#42]
my css looks like this:

```
.bl-widget {
        width: 172px;
        height: 27px;
        border: 1px solid #c0c0c0;
        border-radius: 4px;
        margin-bottom: 10px;
        background: #f9f9f9 url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAABRCAIAAACc+VspAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo2MzEzQkUyNDhCRkExMUUyQjdBRTg1RUM3MzhCN0Y0QSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo2MzEzQkUyNThCRkExMUUyQjdBRTg1RUM3MzhCN0Y0QSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjRBMjg0NDZGOEJGQTExRTJCN0FFODVFQzczOEI3RjRBIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjRBMjg0NDcwOEJGQTExRTJCN0FFODVFQzczOEI3RjRBIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+nVl/8QAAADlJREFUeNpi+P//PxMIMzAwgDGMTQ0a2VwgZsAihqIHlxtIVQfCv3//RuEzMjKCMYxNDRrqJ4AAAwBFHUVtdoNJaQAAAABJRU5ErkJggg==) repeat-x 0 0;
      }
```

and I get this error in production:

```
TypeError: Cannot call method 'replace' of undefined
    at /home/ec2-user/bloglovin-widget/node_modules/express-cdn/lib/main.js:188:16
    at Request._callback (/home/ec2-user/bloglovin-widget/node_modules/express-cdn/lib/main.js:330:5)
    at Request.self.callback (/home/ec2-user/bloglovin-widget/node_modules/express-cdn/node_modules/request/index.js:142:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/ec2-user/bloglovin-widget/node_modules/express-cdn/node_modules/request/index.js:856:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/ec2-user/bloglovin-widget/node_modules/express-cdn/node_modules/request/index.js:808:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:415:13)
```

**Comment by gagalago** [comment]
some update ? can I close ?
